#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   fxc /ECombine /Tps_2_0 /Fhadd.h add.fx
//
//
// Parameters:
//
//   sampler2D g_samSrcColor1;
//   sampler2D g_samSrcColor2;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g_samSrcColor1 s0       1
//   g_samSrcColor2 s1       1
//

    ps_2_0
    def c0, 1, 0, 0, 0
    dcl t0.xy
    dcl t1.xy
    dcl_2d s0
    dcl_2d s1
    texld r0, t0, s0
    texld r1, t1, s1
    add r0.xyz, r0, r1
    mov r0.w, c0.x
    mov oC0, r0

// approximately 5 instruction slots used (2 texture, 3 arithmetic)
#endif

const DWORD g_ps20_Combine[] =
{
    0xffff0200, 0x002cfffe, 0x42415443, 0x0000001c, 0x0000007a, 0xffff0200, 
    0x00000002, 0x0000001c, 0x00000100, 0x00000073, 0x00000044, 0x00000003, 
    0x00000001, 0x00000054, 0x00000000, 0x00000064, 0x00010003, 0x00000001, 
    0x00000054, 0x00000000, 0x61735f67, 0x6372536d, 0x6f6c6f43, 0xab003172, 
    0x000c0004, 0x00010001, 0x00000001, 0x00000000, 0x61735f67, 0x6372536d, 
    0x6f6c6f43, 0x70003272, 0x5f325f73, 0x694d0030, 0x736f7263, 0x2074666f, 
    0x20295228, 0x58443344, 0x68532039, 0x72656461, 0x6d6f4320, 0x656c6970, 
    0x2e392072, 0x322e3830, 0x302e3939, 0x00303030, 0x05000051, 0xa00f0000, 
    0x3f800000, 0x00000000, 0x00000000, 0x00000000, 0x0200001f, 0x80000000, 
    0xb0030000, 0x0200001f, 0x80000000, 0xb0030001, 0x0200001f, 0x90000000, 
    0xa00f0800, 0x0200001f, 0x90000000, 0xa00f0801, 0x03000042, 0x800f0000, 
    0xb0e40000, 0xa0e40800, 0x03000042, 0x800f0001, 0xb0e40001, 0xa0e40801, 
    0x03000002, 0x80070000, 0x80e40000, 0x80e40001, 0x02000001, 0x80080000, 
    0xa0000000, 0x02000001, 0x800f0800, 0x80e40000, 0x0000ffff
};
