#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   fxc /EDofCombine /Tps_2_0 /FhpsPP_DofCombine.h PP_DofCombine.fx
//
//
// Parameters:
//
//   float4 FocalPlane;
//   sampler2D g_samSceneColor;
//   sampler2D g_samSrcColor;
//   sampler2D g_samSrcPosition;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   FocalPlane       c0       1
//   g_samSrcColor    s0       1
//   g_samSrcPosition s1       1
//   g_samSceneColor  s2       1
//
//
// Default values:
//
//   FocalPlane
//     c0   = { 0, 0, 0.2, -0.6 };
//

    ps_2_0
    def c1, 1, 0, 0, 0
    dcl t0.xy
    dcl t1.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    texld r0, t0, s1
    texld r2, t1, s2
    texld r1, t0, s0
    dp4 r0.w, r0, c0
    abs_sat r1.w, r0.w
    lrp r0.xyz, r1.w, r1, r2
    mov r0.w, c1.x
    mov oC0, r0

// approximately 9 instruction slots used (3 texture, 6 arithmetic)
#endif

const DWORD g_ps20_DofCombine[] =
{
    0xffff0200, 0x0045fffe, 0x42415443, 0x0000001c, 0x000000de, 0xffff0200, 
    0x00000004, 0x0000001c, 0x00000100, 0x000000d7, 0x0000006c, 0x00000002, 
    0x00000001, 0x00000078, 0x00000088, 0x00000098, 0x00020003, 0x00000001, 
    0x000000a8, 0x00000000, 0x000000b8, 0x00000003, 0x00000001, 0x000000a8, 
    0x00000000, 0x000000c6, 0x00010003, 0x00000001, 0x000000a8, 0x00000000, 
    0x61636f46, 0x616c506c, 0xab00656e, 0x00030001, 0x00040001, 0x00000001, 
    0x00000000, 0x00000000, 0x00000000, 0x3e4ccccd, 0xbf19999a, 0x61735f67, 
    0x6563536d, 0x6f43656e, 0x00726f6c, 0x000c0004, 0x00010001, 0x00000001, 
    0x00000000, 0x61735f67, 0x6372536d, 0x6f6c6f43, 0x5f670072, 0x536d6173, 
    0x6f506372, 0x69746973, 0x70006e6f, 0x5f325f73, 0x694d0030, 0x736f7263, 
    0x2074666f, 0x20295228, 0x58443344, 0x68532039, 0x72656461, 0x6d6f4320, 
    0x656c6970, 0x2e392072, 0x322e3830, 0x302e3939, 0x00303030, 0x05000051, 
    0xa00f0001, 0x3f800000, 0x00000000, 0x00000000, 0x00000000, 0x0200001f, 
    0x80000000, 0xb0030000, 0x0200001f, 0x80000000, 0xb0030001, 0x0200001f, 
    0x90000000, 0xa00f0800, 0x0200001f, 0x90000000, 0xa00f0801, 0x0200001f, 
    0x90000000, 0xa00f0802, 0x03000042, 0x800f0000, 0xb0e40000, 0xa0e40801, 
    0x03000042, 0x800f0002, 0xb0e40001, 0xa0e40802, 0x03000042, 0x800f0001, 
    0xb0e40000, 0xa0e40800, 0x03000009, 0x80080000, 0x80e40000, 0xa0e40000, 
    0x02000023, 0x80180001, 0x80ff0000, 0x04000012, 0x80070000, 0x80ff0001, 
    0x80e40001, 0x80e40002, 0x02000001, 0x80080000, 0xa0000001, 0x02000001, 
    0x800f0800, 0x80e40000, 0x0000ffff
};
