#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   fxc /EPostProcessPS /Tps_2_0 /FhpsEdgeDetect.h EdgeDetect.fx
//
//
// Parameters:
//
//   float3 LuminanceConv;
//   float2 TexelKernel[4];
//   sampler2D g_samSrcColor;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   TexelKernel   c0       4
//   LuminanceConv c4       1
//   g_samSrcColor s0       1
//
//
// Default values:
//
//   LuminanceConv
//     c4   = { 0.2125, 0.7154, 0.0721, 0 };
//

    ps_2_0
    def c5, -0.5, 1.20000005, 0.5, 5
    dcl t0.xy
    dcl_2d s0
    add r0.xy, t0, c0
    add r3.xy, t0, c1
    add r2.xy, t0, c2
    add r1.xy, t0, c3
    texld r4, r0, s0
    texld r0, t0, s0
    texld r3, r3, s0
    texld r2, r2, s0
    texld r1, r1, s0
    add r4.xyz, -r4, r0
    abs r4.xyz, r4
    add r4.xyz, r4, c5.x
    mad r4.xyz, r4, c5.y, c5.z
    add r3.xyz, r0, -r3
    abs r3.xyz, r3
    add r3.xyz, r3, c5.x
    mad r3.xyz, r3, c5.y, r4
    add r3.xyz, r3, c5.z
    add r2.xyz, r0, -r2
    abs r2.xyz, r2
    add r2.xyz, r2, c5.x
    mad r2.xyz, r2, c5.y, r3
    add r2.xyz, r2, c5.z
    add r0.xyz, r0, -r1
    abs r0.xyz, r0
    add r0.xyz, r0, c5.x
    mad r0.xyz, r0, c5.y, r2
    add r0.xyz, r0, c5.z
    dp3_sat r0.x, c4, r0
    mul r0, r0.x, c5.w
    mov oC0, r0

// approximately 31 instruction slots used (5 texture, 26 arithmetic)
#endif

const DWORD g_ps20_EdgeDetect[] =
{
    0xffff0200, 0x0041fffe, 0x42415443, 0x0000001c, 0x000000cb, 0xffff0200, 
    0x00000003, 0x0000001c, 0x00000100, 0x000000c4, 0x00000058, 0x00040002, 
    0x00000001, 0x00000068, 0x00000078, 0x00000088, 0x00000002, 0x00000004, 
    0x00000094, 0x00000000, 0x000000a4, 0x00000003, 0x00000001, 0x000000b4, 
    0x00000000, 0x696d754c, 0x636e616e, 0x6e6f4365, 0xabab0076, 0x00030001, 
    0x00030001, 0x00000001, 0x00000000, 0x3e59999a, 0x3f372474, 0x3d93a92a, 
    0x00000000, 0x65786554, 0x72654b6c, 0x006c656e, 0x00030001, 0x00020001, 
    0x00000004, 0x00000000, 0x61735f67, 0x6372536d, 0x6f6c6f43, 0xabab0072, 
    0x000c0004, 0x00010001, 0x00000001, 0x00000000, 0x325f7370, 0x4d00305f, 
    0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 0x65646168, 
    0x6f432072, 0x6c69706d, 0x39207265, 0x2e38302e, 0x2e393932, 0x30303030, 
    0xababab00, 0x05000051, 0xa00f0005, 0xbf000000, 0x3f99999a, 0x3f000000, 
    0x40a00000, 0x0200001f, 0x80000000, 0xb0030000, 0x0200001f, 0x90000000, 
    0xa00f0800, 0x03000002, 0x80030000, 0xb0e40000, 0xa0e40000, 0x03000002, 
    0x80030003, 0xb0e40000, 0xa0e40001, 0x03000002, 0x80030002, 0xb0e40000, 
    0xa0e40002, 0x03000002, 0x80030001, 0xb0e40000, 0xa0e40003, 0x03000042, 
    0x800f0004, 0x80e40000, 0xa0e40800, 0x03000042, 0x800f0000, 0xb0e40000, 
    0xa0e40800, 0x03000042, 0x800f0003, 0x80e40003, 0xa0e40800, 0x03000042, 
    0x800f0002, 0x80e40002, 0xa0e40800, 0x03000042, 0x800f0001, 0x80e40001, 
    0xa0e40800, 0x03000002, 0x80070004, 0x81e40004, 0x80e40000, 0x02000023, 
    0x80070004, 0x80e40004, 0x03000002, 0x80070004, 0x80e40004, 0xa0000005, 
    0x04000004, 0x80070004, 0x80e40004, 0xa0550005, 0xa0aa0005, 0x03000002, 
    0x80070003, 0x80e40000, 0x81e40003, 0x02000023, 0x80070003, 0x80e40003, 
    0x03000002, 0x80070003, 0x80e40003, 0xa0000005, 0x04000004, 0x80070003, 
    0x80e40003, 0xa0550005, 0x80e40004, 0x03000002, 0x80070003, 0x80e40003, 
    0xa0aa0005, 0x03000002, 0x80070002, 0x80e40000, 0x81e40002, 0x02000023, 
    0x80070002, 0x80e40002, 0x03000002, 0x80070002, 0x80e40002, 0xa0000005, 
    0x04000004, 0x80070002, 0x80e40002, 0xa0550005, 0x80e40003, 0x03000002, 
    0x80070002, 0x80e40002, 0xa0aa0005, 0x03000002, 0x80070000, 0x80e40000, 
    0x81e40001, 0x02000023, 0x80070000, 0x80e40000, 0x03000002, 0x80070000, 
    0x80e40000, 0xa0000005, 0x04000004, 0x80070000, 0x80e40000, 0xa0550005, 
    0x80e40002, 0x03000002, 0x80070000, 0x80e40000, 0xa0aa0005, 0x03000008, 
    0x80110000, 0xa0e40004, 0x80e40000, 0x03000005, 0x800f0000, 0x80000000, 
    0xa0ff0005, 0x02000001, 0x800f0800, 0x80e40000, 0x0000ffff
};
