#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   fxc /ETreshold /Tps_2_0 /FhpsTreshold.h Treshold.fx
//
//
// Parameters:
//
//   sampler2D g_samSrcColor1;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g_samSrcColor1 s0       1
//

    ps_2_0
    def c0, -2.0999999, 0, 1, 0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    add r0.w, r0.y, r0.x
    add r0.w, r0.z, r0.w
    add r0.w, r0.w, c0.x
    cmp r0.xyz, r0.w, r0, c0.y
    mov r0.w, c0.z
    mov oC0, r0

// approximately 7 instruction slots used (1 texture, 6 arithmetic)
#endif

const DWORD g_ps20_Treshold[] =
{
    0xffff0200, 0x0024fffe, 0x42415443, 0x0000001c, 0x00000057, 0xffff0200, 
    0x00000001, 0x0000001c, 0x00000100, 0x00000050, 0x00000030, 0x00000003, 
    0x00000001, 0x00000040, 0x00000000, 0x61735f67, 0x6372536d, 0x6f6c6f43, 
    0xab003172, 0x000c0004, 0x00010001, 0x00000001, 0x00000000, 0x325f7370, 
    0x4d00305f, 0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 
    0x65646168, 0x6f432072, 0x6c69706d, 0x39207265, 0x2e38302e, 0x2e393932, 
    0x30303030, 0xababab00, 0x05000051, 0xa00f0000, 0xc0066666, 0x00000000, 
    0x3f800000, 0x00000000, 0x0200001f, 0x80000000, 0xb0030000, 0x0200001f, 
    0x90000000, 0xa00f0800, 0x03000042, 0x800f0000, 0xb0e40000, 0xa0e40800, 
    0x03000002, 0x80080000, 0x80550000, 0x80000000, 0x03000002, 0x80080000, 
    0x80aa0000, 0x80ff0000, 0x03000002, 0x80080000, 0x80ff0000, 0xa0000000, 
    0x04000058, 0x80070000, 0x80ff0000, 0x80e40000, 0xa0550000, 0x02000001, 
    0x80080000, 0xa0aa0000, 0x02000001, 0x800f0800, 0x80e40000, 0x0000ffff
};
