#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   fxc /EUpFilter /Tps_2_0 /FhpsUpScale4X.h UpScale4X.fx
//
//
// Parameters:
//
//   sampler2D g_samSrcColor;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   g_samSrcColor s0       1
//

    ps_2_0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    mov oC0, r0

// approximately 2 instruction slots used (1 texture, 1 arithmetic)
#endif

const DWORD g_ps20_UpScale4X[] =
{
    0xffff0200, 0x0024fffe, 0x42415443, 0x0000001c, 0x00000057, 0xffff0200, 
    0x00000001, 0x0000001c, 0x00000100, 0x00000050, 0x00000030, 0x00000003, 
    0x00000001, 0x00000040, 0x00000000, 0x61735f67, 0x6372536d, 0x6f6c6f43, 
    0xabab0072, 0x000c0004, 0x00010001, 0x00000001, 0x00000000, 0x325f7370, 
    0x4d00305f, 0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 
    0x65646168, 0x6f432072, 0x6c69706d, 0x39207265, 0x2e38302e, 0x2e393932, 
    0x30303030, 0xababab00, 0x0200001f, 0x80000000, 0xb0030000, 0x0200001f, 
    0x90000000, 0xa00f0800, 0x03000042, 0x800f0000, 0xb0e40000, 0xa0e40800, 
    0x02000001, 0x800f0800, 0x80e40000, 0x0000ffff
};
